# Generated by Django 2.1.1 on 2018-09-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lateFee', models.IntegerField()),
                ('rentalPrice', models.IntegerField()),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('timeReturned', models.DateField()),
                ('borrowedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.User')),
                ('borrowedObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.Object')),
            ],
        ),
    ]
