# Generated by Django 2.1.1 on 2018-10-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_auto_20181003_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='endTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='startTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='timeBorrowed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='timeReturned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
